SOURCES = main.cpp robot.cpp unit.cpp

OBJECTS = main.o robot.o unit.o

roboticArmSim: main.cpp robot.cpp unit.cpp
	g++ -o roboticArmSim main.cpp robot.cpp unit.cpp

CXXFLAGS = -std=c++11 -D_GNU_SOURCE -Wall
